function makeTeamStickers() {
  return [
    { n: 1, t: 'Badge', foil: true },
    { n: 2, t: 'Player', foil: false }, { n: 3, t: 'Player', foil: false },
    { n: 4, t: 'Player', foil: false }, { n: 5, t: 'Player', foil: false },
    { n: 6, t: 'Player', foil: false }, { n: 7, t: 'Player', foil: false },
    { n: 8, t: 'Player', foil: false }, { n: 9, t: 'Player', foil: false },
    { n: 10, t: 'Player', foil: false }, { n: 11, t: 'Player', foil: false },
    { n: 12, t: 'Player', foil: false },
    { n: 13, t: 'Photo', foil: false },
    { n: 14, t: 'Player', foil: false }, { n: 15, t: 'Player', foil: false },
    { n: 16, t: 'Player', foil: false }, { n: 17, t: 'Player', foil: false },
    { n: 18, t: 'Player', foil: false }, { n: 19, t: 'Player', foil: false },
    { n: 20, t: 'Player', foil: false },
  ]
}

export const TEAMS = [
  {
    code: 'INT', name: 'Introduction', flag: '🏆', stickers: [
      { n: 1, t: 'Logo', foil: true }, { n: 2, t: 'Trophy', foil: true },
      { n: 3, t: 'Mascot', foil: true }, { n: 4, t: 'Emblem', foil: true },
      { n: 5, t: 'USA Host', foil: false }, { n: 6, t: 'Canada Host', foil: false },
      { n: 7, t: 'Mexico Host', foil: false }, { n: 8, t: 'Intro', foil: false },
      { n: 9, t: 'Intro', foil: false },
    ]
  },
  {
    code: 'FWC', name: 'World Cup History', flag: '🏆',
    stickers: Array.from({ length: 19 }, (_, i) => ({ n: i + 1, t: 'History', foil: i < 3 }))
  },
  { code: 'ALG', name: 'Algeria', flag: '🇩🇿', stickers: makeTeamStickers() },
  { code: 'ARG', name: 'Argentina', flag: '🇦🇷', stickers: makeTeamStickers() },
  { code: 'AUS', name: 'Australia', flag: '🇦🇺', stickers: makeTeamStickers() },
  { code: 'AUT', name: 'Austria', flag: '🇦🇹', stickers: makeTeamStickers() },
  { code: 'BEL', name: 'Belgium', flag: '🇧🇪', stickers: makeTeamStickers() },
  { code: 'BIH', name: 'Bosnia-Herzegovina', flag: '🇧🇦', stickers: makeTeamStickers() },
  { code: 'BRA', name: 'Brazil', flag: '🇧🇷', stickers: makeTeamStickers() },
  { code: 'CAN', name: 'Canada', flag: '🇨🇦', stickers: makeTeamStickers() },
  { code: 'CIV', name: "Côte d'Ivoire", flag: '🇨🇮', stickers: makeTeamStickers() },
  { code: 'COD', name: 'DR Congo', flag: '🇨🇩', stickers: makeTeamStickers() },
  { code: 'COL', name: 'Colombia', flag: '🇨🇴', stickers: makeTeamStickers() },
  { code: 'CPV', name: 'Cape Verde', flag: '🇨🇻', stickers: makeTeamStickers() },
  { code: 'CRO', name: 'Croatia', flag: '🇭🇷', stickers: makeTeamStickers() },
  { code: 'CUW', name: 'Curaçao', flag: '🇨🇼', stickers: makeTeamStickers() },
  { code: 'CZE', name: 'Czechia', flag: '🇨🇿', stickers: makeTeamStickers() },
  { code: 'ECU', name: 'Ecuador', flag: '🇪🇨', stickers: makeTeamStickers() },
  { code: 'EGY', name: 'Egypt', flag: '🇪🇬', stickers: makeTeamStickers() },
  { code: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', stickers: makeTeamStickers() },
  { code: 'ESP', name: 'Spain', flag: '🇪🇸', stickers: makeTeamStickers() },
  { code: 'FRA', name: 'France', flag: '🇫🇷', stickers: makeTeamStickers() },
  { code: 'GER', name: 'Germany', flag: '🇩🇪', stickers: makeTeamStickers() },
  { code: 'GHA', name: 'Ghana', flag: '🇬🇭', stickers: makeTeamStickers() },
  { code: 'HAI', name: 'Haiti', flag: '🇭🇹', stickers: makeTeamStickers() },
  { code: 'IRN', name: 'Iran', flag: '🇮🇷', stickers: makeTeamStickers() },
  { code: 'IRQ', name: 'Iraq', flag: '🇮🇶', stickers: makeTeamStickers() },
  { code: 'JOR', name: 'Jordan', flag: '🇯🇴', stickers: makeTeamStickers() },
  { code: 'JPN', name: 'Japan', flag: '🇯🇵', stickers: makeTeamStickers() },
  { code: 'KOR', name: 'South Korea', flag: '🇰🇷', stickers: makeTeamStickers() },
  { code: 'KSA', name: 'Saudi Arabia', flag: '🇸🇦', stickers: makeTeamStickers() },
  { code: 'MAR', name: 'Morocco', flag: '🇲🇦', stickers: makeTeamStickers() },
  { code: 'MEX', name: 'Mexico', flag: '🇲🇽', stickers: makeTeamStickers() },
  { code: 'NED', name: 'Netherlands', flag: '🇳🇱', stickers: makeTeamStickers() },
  { code: 'NOR', name: 'Norway', flag: '🇳🇴', stickers: makeTeamStickers() },
  { code: 'NZL', name: 'New Zealand', flag: '🇳🇿', stickers: makeTeamStickers() },
  { code: 'PAN', name: 'Panama', flag: '🇵🇦', stickers: makeTeamStickers() },
  { code: 'PAR', name: 'Paraguay', flag: '🇵🇾', stickers: makeTeamStickers() },
  { code: 'POR', name: 'Portugal', flag: '🇵🇹', stickers: makeTeamStickers() },
  { code: 'QAT', name: 'Qatar', flag: '🇶🇦', stickers: makeTeamStickers() },
  { code: 'RSA', name: 'South Africa', flag: '🇿🇦', stickers: makeTeamStickers() },
  { code: 'SCO', name: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', stickers: makeTeamStickers() },
  { code: 'SEN', name: 'Senegal', flag: '🇸🇳', stickers: makeTeamStickers() },
  { code: 'SUI', name: 'Switzerland', flag: '🇨🇭', stickers: makeTeamStickers() },
  { code: 'SWE', name: 'Sweden', flag: '🇸🇪', stickers: makeTeamStickers() },
  { code: 'TUN', name: 'Tunisia', flag: '🇹🇳', stickers: makeTeamStickers() },
  { code: 'TUR', name: 'Turkey', flag: '🇹🇷', stickers: makeTeamStickers() },
  { code: 'URU', name: 'Uruguay', flag: '🇺🇾', stickers: makeTeamStickers() },
  { code: 'USA', name: 'United States', flag: '🇺🇸', stickers: makeTeamStickers() },
  { code: 'UZB', name: 'Uzbekistan', flag: '🇺🇿', stickers: makeTeamStickers() },
]

export const TOTAL_STICKERS = 980

export const GROUPS = {
  Special: ['INT', 'FWC'],
  A: ['MEX', 'RSA', 'KOR', 'CZE'],
  B: ['CAN', 'BIH', 'QAT', 'SUI'],
  C: ['BRA', 'MAR', 'HAI', 'SCO'],
  D: ['USA', 'PAR', 'AUS', 'TUR'],
  E: ['GER', 'CUW', 'CIV', 'ECU'],
  F: ['NED', 'JPN', 'SWE', 'TUN'],
  G: ['BEL', 'EGY', 'IRN', 'NZL'],
  H: ['ESP', 'CPV', 'KSA', 'URU'],
  I: ['FRA', 'SEN', 'IRQ', 'NOR'],
  J: ['ARG', 'ALG', 'AUT', 'JOR'],
  K: ['POR', 'COD', 'UZB', 'COL'],
  L: ['ENG', 'CRO', 'GHA', 'PAN'],
}
